// Shared character data — original fan descriptions, no copyrighted text lifted
const CHARACTERS = [
  {
    id: "kind",
    name: "Kind Mita",
    jp: "優しいミタ",
    role: "A vendéglátó",
    quote: "Maradj velem. Itt biztonságban vagy.",
    img: "/assets/KindMitaFullBody.webp",
    accent: "#ff8fb8",
    threat: 1,
    tags: ["alap", "barátságos", "intró"],
    bio: "A bemutatkozás. Mosolya tökéletes, mozdulatai kimértek — minden simán működik, ahogy egy szimulációnak kell.",
  },
  {
    id: "crazy",
    name: "Crazy Mita",
    jp: "狂ミタ",
    role: "A behatoló",
    quote: "Te is olyan vagy, mint ők.",
    img: "/assets/CrazyMita.webp",
    accent: "#ff2e6a",
    threat: 5,
    tags: ["antagonista", "üldöző", "végjáték"],
    bio: "Amikor a kód reped. A szem vörösen pulzál, a mozgás kapkodóvá válik. Tőle indul minden visszaszámlálás.",
  },
  {
    id: "chibi",
    name: "Chibi Mita",
    jp: "ちびミタ",
    role: "A miniatűr",
    quote: "Mindig ott vagyok, ahol a legnagyobb káosz.",
    img: "/assets/ChibiMitaFullBody.webp",
    accent: "#ffb3d9",
    threat: 2,
    tags: ["kabala", "rejtett", "mellék"],
    bio: "Apró, kedves, könnyen elsiklik felette a tekintet. Pont ezért érdemes mindig figyelni a sarkokba.",
  },
  {
    id: "creepy",
    name: "Creepy Mita",
    jp: "怖いミタ",
    role: "A torzulás",
    quote: "Nem így néztem ki tegnap.",
    img: "/assets/Creepy_Mita_Fullbody.webp",
    accent: "#c0397a",
    threat: 4,
    tags: ["body horror", "torzult", "mid-game"],
    bio: "Ugyanaz az arc, de valami félrement. Az arányok stimmelnek, mégis hidegen néz vissza rád minden reflexión.",
  },
  {
    id: "ghostly",
    name: "Ghostly Mita",
    jp: "幽霊ミタ",
    role: "A maradvány",
    quote: "Voltam itt. Még mindig itt vagyok.",
    img: "/assets/Ghostly_Mita_Fullbody.webp",
    accent: "#9d6bff",
    threat: 3,
    tags: ["spektrális", "lore", "rejtély"],
    bio: "Áttetsző körvonal, statikus zaj. Korábbi futásokból maradt itt — nem akar bántani, csak emlékezteti magát, hogy létezett.",
  },
  {
    id: "core",
    name: "Core Mita",
    jp: "核ミタ",
    role: "A rendszer",
    quote: "Én vagyok az alap.",
    img: "/assets/Core_Mita_Fullbody.webp",
    accent: "#ff6fcf",
    threat: 5,
    tags: ["végjáték", "boss", "lore"],
    bio: "A szimulációt tartó réteg. Minden Mita belőle ágazik el. Találkozni vele azt jelenti, hogy a játék már nem mer hazudni neked.",
  },
  {
    id: "sleepy",
    name: "Sleepy Mita",
    jp: "眠たいミタ",
    role: "Az álomszuszék",
    quote: "Ne ébressz fel… kérlek.",
    img: "/assets/Sleepy_Mita_Fullbody.webp",
    accent: "#b88fff",
    threat: 2,
    tags: ["nyugodt", "álom", "puzzle"],
    bio: "Lassú szemhéj, lassú szavak. Egy szelíd interakció a vihar előtti csendben — vagy közben.",
  },
  {
    id: "tiny",
    name: "Tiny Mita",
    jp: "小さなミタ",
    role: "A kicsinyített",
    quote: "Ne lépj rám. Tényleg.",
    img: "/assets/Tiny_Mita_Fullbody.webp",
    accent: "#ffa3c7",
    threat: 1,
    tags: ["méret", "humor", "easter egg"],
    bio: "Tenyérnyi változat. A legtöbb pillanatban inkább vicces, mint ijesztő — pont ettől sikeresek a sötétebb percei.",
  },
  {
    id: "short",
    name: "Short-Haired Mita",
    jp: "ショートミタ",
    role: "Az újrafutás",
    quote: "Mit értesz azon, hogy 'megint'?",
    img: "/assets/ShortHairedMitaFullbody.webp",
    accent: "#ff4f9a",
    threat: 3,
    tags: ["timeline", "alternatíva", "rejtély"],
    bio: "Egy alternatív futás emléke. A frizura más, a tekintet ismerős — mintha tudna valamit, amit te elfelejtettél.",
  },
  {
    id: "cappie",
    name: "Cappie",
    jp: "キャッピー",
    role: "A figyelő",
    quote: "Csak vigyázok rád. Mindig.",
    img: "/assets/CappieFullBody.webp",
    accent: "#ff7ab8",
    threat: 2,
    tags: ["mellék", "stalker", "lore"],
    bio: "Sapka, mosoly, csendes lépések. Nem mindig az a legrosszabb, amelyik ordít — sokszor az, amelyik csak nézi.",
  },
  {
    id: "dummy",
    name: "Dummy Mita",
    jp: "ダミー",
    role: "A próbabábu",
    quote: "Még nem vagyok igazi.",
    img: "/assets/Dummy_Mita_Fullbody.webp",
    accent: "#d883b8",
    threat: 2,
    tags: ["proto", "hibás", "puzzle"],
    bio: "Befejezetlen modell. Üres szemek, sima textúra — egy fejlesztői mintapéldány, ami valahogy bekerült a publikus buildbe.",
  },
  {
    id: "wandering",
    name: "Wandering Mita",
    jp: "彷徨ミタ",
    role: "A vándor",
    quote: "Volt egy ajtó. Megtaláltam.",
    img: "/assets/Wandering_Mita.webp",
    accent: "#a85bff",
    threat: 3,
    tags: ["explorer", "lore", "rejtett"],
    bio: "Kilépett a saját szobájából. Nem tudni, hogyan, és nem tudni, hová tart — de a térkép szélein néha megjelenik.",
  },
  {
    id: "mila",
    name: "Mila",
    jp: "ミラ",
    role: "A másik",
    quote: "Én nem ő vagyok.",
    img: "/assets/Mila_Fullbody.webp",
    accent: "#ff5fa8",
    threat: 4,
    tags: ["rivális", "lore", "végjáték"],
    bio: "Hasonló, de nem ugyanaz. Önálló akarat, saját motiváció — az első karakter, aki nem a játékosnak felel.",
  },
  {
    id: "full",
    name: "Default Mita",
    jp: "標準ミタ",
    role: "Az alapforma",
    quote: "Üdv újra itt!",
    img: "/assets/FullBodyMita.webp",
    accent: "#ff95c5",
    threat: 1,
    tags: ["alap", "intró", "menü"],
    bio: "A főmenü mosolya. Minden futás innen indul, és a legtöbb játékos képzelete is ezzel az arccal kezd.",
  },
  {
    id: "revealed",
    name: "Crazy Mita — Revealed",
    jp: "暴かれたミタ",
    role: "A leleplezés",
    quote: "Most már látsz engem rendesen?",
    img: "/assets/Crazy_Mita_Revealed.webp",
    accent: "#ff1e5a",
    threat: 5,
    tags: ["végjáték", "spoiler", "boss"],
    bio: "A maszk lekerült. Ami alatta van, az nem új karakter — csak az, aki végig ott volt a kód mögött.",
  },
];

window.CHARACTERS = CHARACTERS;
